'use strict';

/**
 * Define default options.
 */

module.exports = function options_(app) {
  app.option({
    toc: {append: '\n\n_(Table of contents generated by [verb])_'}
  });

  // engines
  app.option('view engine', 'md');

  // routing
  app.option('router methods', ['onInit', 'onRender']);
  app.enable('case sensitive routing');
  app.enable('strict routing');

  // delimiters
  app.option('layoutDelims', ['<<%', '%>>']);
  app.option('escapeDelims', {
    from: ['{%%', '%}'],
    to: ['{%', '%}']
  });
};
