#!/usr/bin/env fish

# Borrowed from gulp:

# Usage:
#
# To enable fish <tab> completion for verb, add the following line to
# your ~/.config/fish/config.fish file:
#
# verb --completion=fish | source

complete -c verb -a "(verb --tasks-simple)" -f
