'use strict';

var install = [
  'Install with [npm](https://www.npmjs.com/)',
  '',
  '```sh',
  '$ npm i {%= name %}{%= save === true ? " --save" : "" %}',
  '```'
].join('\n');

module.exports = {
  'install-npm.md': install,
  'install.md': install,

  'install-bower.md': [
    'Install with [bower](http://bower.io/)',
    '',
    '```sh',
    '$ bower install {%= name %}{%= save === true ? " --save" : "" %}',
    '```'
  ].join('\n'),

  'install-global.md': [
    'Install globally with [npm](https://www.npmjs.com/)',
    '',
    '```sh',
    '$ npm i -g {%= name %}',
    '```'
  ].join('\n'),

  'tests.md': [
    'Install dev dependencies:',
    '',
    '```sh',
    '$ npm i -d && npm test',
    '```'
  ].join('\n'),

  'author.md': [
    '**{%= author.name %}**',
    '',
    '+ [github/{%= author.username %}](https://github.com/{%= author.username %})',
    '+ [twitter/{%= author.twitter %}](http://twitter.com/{%= author.twitter %})'
  ].join('\n'),

  'contributing.md': 'Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](https://github.com/{%= author.username %}/{%= name %}/issues/new).',

  'footer.md': '_This file was generated by [{%= runner.name %}]({%= runner.url %}) on {%= date() %}._'
};
